In [125]:
from pathlib import Path

import re
import pandas as pd
import numpy as np

from ucimlrepo import fetch_ucirepo # Official library to import dataset from ucimlrepo

In [71]:
# Fetch the dataset with this code 

# adult = fetch_ucirepo(id=2) 
  
# # data (as pandas dataframes) 
# X = adult.data.features 
# y = adult.data.targets 
  
# # metadata 
# print(adult.metadata) 
  
# # variable information 
# print(adult.variables)

In [ ]:
# Instead of fetching the dataset again and again , I have simpdy downloaded the folder for the adult set .
# I will pe using the Path to import the set directly without any recurrent fetching.

In [73]:
BASE_PATH = Path.cwd().parent / "datasets" / "adult"

TRAIN_PATH = BASE_PATH / "adult.data"
TEST_PATH = BASE_PATH / "adult.test"

In [74]:
# Column names from adult.names : 
""" 
age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

"""

columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "salary"
]

In [76]:
# Best practice is to use exceptional handling here but for now just load the training and testing set 
train = pd.read_csv(TRAIN_PATH, header=None, names=columns)
test = pd.read_csv(TEST_PATH, header=None, names=columns, skiprows=1)

# The dataset did not contain the column names but were given to us in a seperate txtfile.
# Also the y column had a corrupt first row which we skip for now.

In [77]:
train.shape

(32561, 15)

In [78]:
test.shape

(16281, 15)

In [79]:
train.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [80]:
test.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [82]:
train.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
salary            0
dtype: int64

In [83]:
test.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
salary            0
dtype: int64

In [106]:
# For precaution anyways.
train = train.dropna()
test = test.dropna()

# EDA (Compdete dataset)

In [85]:
# Now for further EDA analysis I will concat both the dataset .

In [94]:
df = pd.concat([train,test],axis=0)

In [95]:
df.shape # The combined shape

(48842, 15)

In [96]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [117]:
# A quick initial analysis function 

def examine_dataframe(df):
    print("-"*100)
    print(f'NOTE : Column names will be converted to lower case and trimming all the white spaces.')
    print("-"*100)
    df.columns = [x.lower().strip().replace(" ","_") for x in df.columns]
    print(f"Dataframe shape : {df.shape}")
    print("-"*100)
    print(f"Memory Usage : {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
    print("-"*100)
    print(f"Column Dtypes: \n{df.dtypes.value_counts()}")
    print("-"*100)
    print(f'Quick overview of all columns: ')
    columns_df = pd.DataFrame({
                'column' : df.columns,
                'dtype' : [x for x in df.dtypes],
                '#unique_values' : [df[x].nunique() for x in df.columns],
                '#non_null_values' : df.notna().sum().tolist() ,
                '#null_values' : df.isna().sum().tolist() ,
                '%null_values' : [f'{x:.2f}' for x in ((df.isna().sum()/df.shape[0])*100).to_list()]
                
        })
    return (columns_df)

In [118]:
examine_dataframe(df)

----------------------------------------------------------------------------------------------------
NOTE : Column names will be converted to lower case and trimming all the white spaces.
----------------------------------------------------------------------------------------------------
Dataframe shape : (48842, 15)
----------------------------------------------------------------------------------------------------
Memory Usage : 27.28 MB
----------------------------------------------------------------------------------------------------
Column Dtypes:
object    9
int64     6
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
Quick overview of all columns:

,column,dtype,#unique_values,#non_null_values,#null_values,%null_values
0,age,int64,74,48842,0,0.00
1,workclass,object,9,48842,0,0.00
2,fnlwgt,int64,28523,48842,0,0.00
3,education,object,16,48842,0,0.00
4,education-num,int64,16,48842,0,0.00
5,marital-status,object,7,48842,0,0.00
6,occupation,object,15,48842,0,0.00
7,relationship,object,6,48842,0,0.00
8,race,object,5,48842,0,0.00
9,sex,object,2,48842,0,0.00
10,capital-gain,int64,123,48842,0,0.00
11,capital-loss,int64,99,48842,0,0.00
12,hours-per-week,int64,96,48842,0,0.00
13,native-country,object,42,48842,0,0.00
14,salary,object,4,48842,0,0.00

In [119]:
# Changed the loading method from polars to pandas ---> I saw a huge difference.
# First of many cols were automatically treated as str in polars but here pandas treat them as numeric (int).
# There was an empty row in both train and test set which is not present in pandas.

# Better interpretibility

In [105]:
# The dataframe contains both numeric and string values together .

# The dataset has a high cardinality columns .
# Suitable strategy has to be devised to handle each categorical column.

In [110]:
df.sample(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
5065,22,Private,450695,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K.
13177,20,?,58740,Some-college,10,Never-married,?,Own-child,White,Male,0,0,15,United-States,<=50K
10799,45,Local-gov,215862,Doctorate,16,Married-civ-spouse,Exec-managerial,Husband,White,Male,7688,0,45,United-States,>50K
4124,25,Private,511331,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0,0,38,United-States,<=50K
21577,37,Self-emp-not-inc,68899,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,2129,40,United-States,<=50K

In [102]:
# This was just a guess but looking closely we found out that dropping nans was just not enough .
# It was a mere trap , the real missing values hiding beneath have also have a "?" symbol attached .

# We have to hunt these symbols and other suspects for cleaning.

In [126]:
# We will use regex patterns to search for all the "?" cleanly.

# Define the regex pattern (escaping the ? character)
pattern = r'\?'

# Scan every cell, convert to string, and apply regex search
mask = df.map(lambda cell: bool(re.search(pattern, str(cell)))).any(axis=1)

# 3. Filter the DataFrame
filtered_df = df[mask]

In [128]:
len(filtered_df)

3620

In [129]:
# We have like 3620 rows containg such "?" values .

In [130]:
# We need to replace these values with nan in their place

In [136]:
df = df.replace(r'.*\?.*', np.nan, regex=True)

In [142]:
# Now are not actually done with fixing inconsitencies , there may or may not be some other dirty string present in each columns .
# To check this we will perform value_counts() for each column to not only clean the dirty columns but also find suitable strategy for encoding later.

In [157]:
df.head(1)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K

In [160]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [165]:
for x in df.select_dtypes("object").columns : 
    print(df[x].value_counts())
    print()

workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

education
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: count, dtype: int64

marital-status
Married-civ-spouse       22379
Never-married            16117
Divorced                  6633
Separated                 1530
Widowed                   1518
Married-spouse-absent      628
Married-AF-spouse           37
Name: count, dtype: int64

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

relationship
Husband           19716
Not-in-family     12583
Own-child          7581
Unmarried          5125
Wife               2331
Other-relative     1506
Name: count, dtype: int64

race
White                 41762
Black                  4685
Asian-Pac-Islander     1519
Amer-Indian-Eskimo      470
Other                   406
Name: count, dtype: int64

sex
Male      32650
Female    16192
Name: count, dtype: int64

native-country
United-States                 43832
Mexico                          951
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Outlying-US(Guam-USVI-etc)       23
Laos                             23
Yugoslavia                       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

salary
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [166]:
" Evaluation on unique values of each column"

# education : 

# THERE ARE NO dirty string present but we have to group this multiple columns into a single one .
# Doing this would not only avoid high cardinality but also would be better for the model and encoding process.
 
# marital-status:
# Similar to the education column ---> Find such grouping strategy for workclass that converts these columns into a few number of classes

# relationship : 
# The column will have a high correlation with marital-status in correlation graph

# sex:
# there is a weight imbalance present.

# salary 
# there are two extra dirty unique values.

# country 
# As expected has a high amount of cardinality

' Evaluation on unique values of each column'