In [157]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,accuracy_score,classification_report,confusion_matrix

In [106]:
df = pd.read_csv('adult.csv')

In [107]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [109]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [110]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [111]:
for x in ['workclass','education','marital-status', 'occupation', 'relationship', 'race', 'gender','native-country','income'] :

    if len(df[x]) > 10:
        print(x)
        print()
        print(df[x].unique())
        print()

workclass

['Private' 'Local-gov' '?' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked']

education

['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool']

marital-status

['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse']

occupation

['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Priv-house-serv'
 'Transport-moving' 'Handlers-cleaners' 'Armed-Forces']

relationship

['Own-child' 'Husband' 'Not-in-family' 'Unmarried' 'Wife' 'Other-relative']

race

['Black' 'White' 'Asian-Pac-Islander' 'Other' 'Amer-Indian-Eskimo']

gender

['Male' 'Female']

native-country

['United-States' '?' 'Peru' 'Guatemala' 'Mexico' 'Dominican-Republic'
 'Ireland' 'Germany' 'Philippines' 'Thailand' 'Haiti' 'El-Salvador'
 'Puerto-Rico' 'Vietnam' 'South' 'Columbia' 'Japan' 'India' 'Cambodia'
 'Poland' 'Laos' 'England' 'Cuba' 'Taiwan' 'Italy' 'Canada' 'Portugal'
 'China' 'Nicaragua' 'Honduras' 'Iran' 'Scotland' 'Jamaica' 'Ecuador'
 'Yugoslavia' 'Hungary' 'Hong' 'Greece' 'Trinadad&Tobago'
 'Outlying-US(Guam-USVI-etc)' 'France' 'Holand-Netherlands']

income

['<=50K' '>50K']

In [112]:
df['gender']

0          Male
1          Male
2          Male
3          Male
4        Female
          ...
48837    Female
48838      Male
48839    Female
48840      Male
48841    Female
Name: gender, Length: 48842, dtype: object

In [113]:
df['gender'] = df['gender'].map(
                                    {
                                                'Male' : 1,
                                                'Female' : 0
                                    }
)

In [114]:
df['gender']

0        1
1        1
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    1
48841    0
Name: gender, Length: 48842, dtype: int64

In [115]:
df = df.drop(columns='education')

In [124]:
df.head()

,age,workclass,fnlwgt,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,7,Never-married,Machine-op-inspct,Own-child,Black,1,0,0,40,United-States,0
1,38,Private,89814,9,Married-civ-spouse,Farming-fishing,Husband,White,1,0,0,50,United-States,0
2,28,Local-gov,336951,12,Married-civ-spouse,Protective-serv,Husband,White,1,0,0,40,United-States,1
3,44,Private,160323,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,1,7688,0,40,United-States,1
4,18,NaN,103497,10,Never-married,NaN,Own-child,White,0,0,0,30,United-States,0

In [117]:
df = df.replace('?',np.nan)

In [130]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer

In [119]:
'''
Theoretically, OrdinalEncoder should be reserved for features with a natural rank (like education or size). Using it on nominal data (like occupation or country) implies a fake order (e.g., "Doctor" is greater than "Farmer") that doesn't exist Scikit-Learn OrdinalEncoder Docs.
However, in Tree-Based Models (like your BaggingClassifier using DecisionTreeClassifier), we often "cheat" and use it for high-cardinality features for two practical reasons:
The "Sparsity" Problem: If you use OneHotEncoder on native-country, you add 40+ columns. If a tree splits on "Country_Greece", it only isolates a tiny fraction of data, making the split very weak Scikit-Learn OneHotEncoder Docs.
Tree Logic: Decision trees can perform multiple splits on a single numerical column to isolate specific integer values, effectively "finding" the categories even if the order is arbitrary.
'''

'\nTheoretically, OrdinalEncoder should be reserved for features with a natural rank (like education or size). Using it on nominal data (like occupation or country) implies a fake order (e.g., "Doctor" is greater than "Farmer") that doesn\'t exist Scikit-Learn OrdinalEncoder Docs.\nHowever, in Tree-Based Models (like your BaggingClassifier using DecisionTreeClassifier), we often "cheat" and use it for high-cardinality features for two practical reasons:\nThe "Sparsity" Problem: If you use OneHotEncoder on native-country, you add 40+ columns. If a tree splits on "Country_Greece", it only isolates a tiny fraction of data, making the split very weak Scikit-Learn OneHotEncoder Docs.\nTree Logic: Decision trees can perform multiple splits on a single numerical column to isolate specific integer values, effectively "finding" the categories even if the order is arbitrary.\n'

In [ ]:
coloumns_for_ohe = ['workclass','marital-status','relationship','race']
columns_for_onc = ['occupation','native-country']

In [ ]:
le = LabelEncoder()
df['income'] = le.fit_transform(df['income'])

In [122]:
df['income']

0        0
1        0
2        1
3        1
4        0
        ..
48837    0
48838    1
48839    0
48840    0
48841    1
Name: income, Length: 48842, dtype: int64

In [123]:
df['income'].unique()

array([0, 1])

In [133]:
from sklearn.ensemble import BaggingClassifier

In [147]:
onc_and_imputation= Pipeline([
                            ('simple_imputer',SimpleImputer(strategy='most_frequent')),
                            ('onc_encoder',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1))
])

In [148]:
ohe_and_imputation= Pipeline([
                            ('simple_imputer',SimpleImputer(strategy='most_frequent')),
                            ('onc_encoder',OneHotEncoder(sparse_output=False,handle_unknown='ignore'))
])

In [149]:
preprocessor = ColumnTransformer(
                    transformers = [
                                        ('ohe',ohe_and_imputation,coloumns_for_ohe),
                                        ('onc',onc_and_imputation,columns_for_onc)
                    ],
        remainder = 'passthrough'
)

In [ ]:
main_pipe = Pipeline([
                            ('processor',preprocessor),
                            ('bgf',BaggingClassifier(
                                                                        n_estimators = 100,
                                                                        n_jobs = -1,
                                                                        bootstrap = True,
                                                                        # oob_score = True ,
                                                                        

                            ))
])

In [151]:
X = df.drop(columns = ['income'])
y = df['income']

In [152]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [153]:
main_pipe

Pipeline(steps=[('processor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  Pipeline(steps=[('simple_imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onc_encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['workclass',
                                                   'marital-status',
                                                   'relationship', 'race']),
                                                 ('onc',
                                                  Pipeline(steps=[('simple_imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onc_encoder',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['occupation',
                                                   'native-country'])])),
                ('bgf', BaggingClassifier(n_jobs=-1))])

In [154]:
main_pipe.fit(X_train,y_train)
y_pred = main_pipe.predict(X_test)

In [ ]:
cvs = cross_val_score(
                    main_pipe,
                    X,
                    y,
                    cv = 10
)

In [156]:
accuracy_score(y_test,y_pred)

0.8566895280990889