In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [2]:
df = pd.read_csv('dermatology_database_1.csv')

In [4]:
df.head()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3

In [5]:
df.tail()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_granular_layer,vacuolisation_damage_basal_layer,spongiosis,saw_tooth_appearance_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_mononuclear_infiltrate,band_like_infiltrate,age,class
361,2,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,2,0,25,4
362,3,2,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,2,0,36,4
363,3,2,2,2,3,2,0,2,0,0,...,0,3,0,3,0,0,2,3,28,3
364,2,1,3,1,2,3,0,2,0,0,...,0,2,0,1,0,0,2,3,50,3
365,3,2,2,0,0,0,0,0,3,3,...,2,0,0,0,0,0,3,0,35,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   erythema                             366 non-null    int64
 1   scaling                              366 non-null    int64
 2   definite_borders                     366 non-null    int64
 3   itching                              366 non-null    int64
 4   koebner_phenomenon                   366 non-null    int64
 5   polygonal_papules                    366 non-null    int64
 6   follicular_papules                   366 non-null    int64
 7   oral_mucosal_involvement             366 non-null    int64
 8   knee_and_elbow_involvement           366 non-null    int64
 9   scalp_involvement                    366 non-null    int64
 10  family_history                       366 non-null    int64
 11  melanin_incontinence                 366 non-null    int64
 12  eosinophils_infiltrate               366 non-null    int64
 13  PNL_infiltrate                       366 non-null    int64
 14  fibrosis_papillary_dermis            366 non-null    int64
 15  exocytosis                           366 non-null    int64
 16  acanthosis                           366 non-null    int64
 17  hyperkeratosis                       366 non-null    int64
 18  parakeratosis                        366 non-null    int64
 19  clubbing_rete_ridges                 366 non-null    int64
 20  elongation_rete_ridges               366 non-null    int64
 21  thinning_suprapapillary_epidermis    366 non-null    int64
 22  spongiform_pustule                   366 non-null    int64
 23  munro_microabcess                    366 non-null    int64
 24  focal_hypergranulosis                366 non-null    int64
 25  disappearance_granular_layer         366 non-null    int64
 26  vacuolisation_damage_basal_layer     366 non-null    int64
 27  spongiosis                           366 non-null    int64
 28  saw_tooth_appearance_retes           366 non-null    int64
 29  follicular_horn_plug                 366 non-null    int64
 30  perifollicular_parakeratosis         366 non-null    int64
 31  inflammatory_mononuclear_infiltrate  366 non-null    int64
 32  band_like_infiltrate                 366 non-null    int64
 33  age                                  366 non-null    str
 34  class                                366 non-null    int64
dtypes: int64(34), str(1)
memory usage: 100.2 KB