In [1]:
from sklearn.model_selection import train_test_split,cross_val_score    
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.metrics import r2_score,root_mean_squared_error

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [16]:
df = pd.read_csv('diabetes.csv')

In [17]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [18]:
X,y = df.drop(columns=['Outcome']),df['Outcome']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2) # Splitting the dataset

In [20]:
alphas = [0.1 , 1 , 10 , 15 , 25, 50] # Test values of alpha
weights = []

for alpha in alphas:
    las = Ridge(alpha=alpha) # Instantiation with current alpha value
    las.fit(X_train,y_train) # Fit the training set 
    y_pred_las = las.predict(X_test) # Predict using Lasso model 
    weights.append(las.coef_)
weights_df = pd.DataFrame(weights,columns=df.drop(columns=['Outcome']).columns,index=alphas)

In [21]:
weights_df # This is the weights and how they are updated as the value of alpha increases

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Pedigree,Age
0.1,0.026114,0.005993,-0.001979,0.000167,-0.000186,0.012864,0.107259,0.001898
1.0,0.026103,0.005994,-0.001980,0.000170,-0.000186,0.012865,0.105745,0.001902
10.0,0.025999,0.006005,-0.001989,0.000196,-0.000182,0.012876,0.092663,0.001937
15.0,0.025946,0.006011,-0.001992,0.000207,-0.000180,0.012880,0.086703,0.001954
25.0,0.025850,0.006020,-0.001999,0.000227,-0.000176,0.012887,0.076820,0.001983
50.0,0.025642,0.006035,-0.002009,0.000261,-0.000171,0.012894,0.059778,0.002040