In [5]:
import polars as pl
from pathlib import Path

In [6]:
BASE_PATH = Path.cwd().parent / "titanic-competition"
TRAIN_PATH = BASE_PATH / "train.csv"

In [9]:
# As we saw there are two approaches : lazy and eager
# One loads the data into ram(but still better than pandas), and stores the workflow to follow when loading data from path.

eager_df = pl.read_csv(TRAIN_PATH)
lazy_df = pl.scan_csv(TRAIN_PATH)

In [10]:
# Now let's peek at the head 
eager_df.head()

shape: (5, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr.        ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry     ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

In [12]:
# Look at the cleanliness and format .
# Compared to pandas a much more descriptive and informative peeking
# Also looking closely above , it first loads the shape of the slice and then loads the data.

In [14]:
# Now instead of info here we have scheme which showcases all the colnames and it's dtype immediately each in a tuple.
eager_df.schema

Schema([('PassengerId', Int64),
        ('Survived', Int64),
        ('Pclass', Int64),
        ('Name', String),
        ('Sex', String),
        ('Age', Float64),
        ('SibSp', Int64),
        ('Parch', Int64),
        ('Ticket', String),
        ('Fare', Float64),
        ('Cabin', String),
        ('Embarked', String)])

In [21]:
# Many functions have same name compared to pandas .
# The creators of Polars wanted the transition to feel familiar.
# The real difference begins when we start manipulating the data.

eager_df.head()
eager_df.shape
eager_df.columns
eager_df.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

In [23]:
eager_df.sample(5)

shape: (5, 12)
┌─────────────┬──────────┬────────┬─────────────────┬───┬──────────┬──────────┬─────────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name            ┆ … ┆ Ticket   ┆ Fare     ┆ Cabin   ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---             ┆   ┆ ---      ┆ ---      ┆ ---     ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str             ┆   ┆ str      ┆ f64      ┆ str     ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════╪═══╪══════════╪══════════╪═════════╪══════════╡
│ 679         ┆ 0        ┆ 3      ┆ Goodwin, Mrs.   ┆ … ┆ CA 2144  ┆ 46.9     ┆ null    ┆ S        │
│             ┆          ┆        ┆ Frederick       ┆   ┆          ┆          ┆         ┆          │
│             ┆          ┆        ┆ (Augus…         ┆   ┆          ┆          ┆         ┆          │
│ 848         ┆ 0        ┆ 3      ┆ Markoff, Mr.    ┆ … ┆ 349213   ┆ 7.8958   ┆ null    ┆ C        │
│             ┆          ┆        ┆ Marin           ┆   ┆          ┆          ┆         ┆          │
│ 805         ┆ 1        ┆ 3      ┆ Hedman, Mr.     ┆ … ┆ 347089   ┆ 6.975    ┆ null    ┆ S        │
│             ┆          ┆        ┆ Oskar Arvid     ┆   ┆          ┆          ┆         ┆          │
│ 845         ┆ 0        ┆ 3      ┆ Culumovic, Mr.  ┆ … ┆ 315090   ┆ 8.6625   ┆ null    ┆ S        │
│             ┆          ┆        ┆ Jeso            ┆   ┆          ┆          ┆         ┆          │
│ 300         ┆ 1        ┆ 1      ┆ Baxter, Mrs.    ┆ … ┆ PC 17558 ┆ 247.5208 ┆ B58 B60 ┆ C        │
│             ┆          ┆        ┆ James (Helene   ┆   ┆          ┆          ┆         ┆          │
│             ┆          ┆        ┆ DeL…            ┆   ┆          ┆          ┆         ┆          │
└─────────────┴──────────┴────────┴─────────────────┴───┴──────────┴──────────┴─────────┴──────────┘

In [ ]:
# We cannnot do boolean masking like pandas and we strictly need to follow filter function for effecient optimized code.

In [42]:
# With pl.col() we can create expression to filter out effeciently.
# NOTE :  This is not a boolean array as eager_df[eager_df['Sex'=='female']] but an expression
type(pl.col("Sex")) # We can clearly see that this is a type of expression

polars.expr.expr.Expr

In [37]:
female_survivor = eager_df.filter(
                    pl.col("Sex") == "female",
                    pl.col("Survived") == 1
)

In [38]:
female_survivor

shape: (233, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 9           ┆ 1        ┆ 3      ┆ Johnson, Mrs.     ┆ … ┆ 347742    ┆ 11.1333 ┆ null  ┆ S        │
│             ┆          ┆        ┆ Oscar W (Elisabe… ┆   ┆           ┆         ┆       ┆          │
│ 10          ┆ 1        ┆ 2      ┆ Nasser, Mrs.      ┆ … ┆ 237736    ┆ 30.0708 ┆ null  ┆ C        │
│             ┆          ┆        ┆ Nicholas (Adele   ┆   ┆           ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…                ┆   ┆           ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                 ┆ … ┆ …         ┆ …       ┆ …     ┆ …        │
│ 875         ┆ 1        ┆ 2      ┆ Abelson, Mrs.     ┆ … ┆ P/PP 3381 ┆ 24.0    ┆ null  ┆ C        │
│             ┆          ┆        ┆ Samuel (Hannah W… ┆   ┆           ┆         ┆       ┆          │
│ 876         ┆ 1        ┆ 3      ┆ Najib, Miss.      ┆ … ┆ 2667      ┆ 7.225   ┆ null  ┆ C        │
│             ┆          ┆        ┆ Adele Kiamie      ┆   ┆           ┆         ┆       ┆          │
│             ┆          ┆        ┆ "Jan…             ┆   ┆           ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.      ┆ … ┆ 11767     ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily   ┆   ┆           ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…                ┆   ┆           ┆         ┆       ┆          │
│ 881         ┆ 1        ┆ 2      ┆ Shelley, Mrs.     ┆ … ┆ 230433    ┆ 26.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William (Imanita… ┆   ┆           ┆         ┆       ┆          │
│ 888         ┆ 1        ┆ 1      ┆ Graham, Miss.     ┆ … ┆ 112053    ┆ 30.0    ┆ B42   ┆ S        │
│             ┆          ┆        ┆ Margaret Edith    ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

In [43]:
# Polars isn't built around DataFrames.It's built around expressions.